version: '3'
services:
  frontend:
    build: frontend/    # Especificamos o contexto, ou seja, a pasta onde está o Dockerfile.
    restart: on-failure # Reinicia o container caso ocorra alguma falha 
    ports:
      - 3000:3000
    depends_on:
      - backend   # Executa antes de executar o atual 
  backend:
    build: backend/     # Mesmo caso aqui.
    restart: on-failure # Reinicia o container caso ocorra alguma falha
    ports:
      - 3001:3001
    environment:
      - DB_HOST=database # Variável que se conecta ao banco de dados
    depends_on:
      - database  # Executa antes de executar o atual
  database:
    image: betrybe/docker-compose-example-database:v1    # Especificamos a Imagem Docker diretamente.
    restart: on-failure # Reinicia o container caso ocorra alguma falha